fixed newline bug

diff --git a/pcsync b/pcsync
--- a/pcsync
+++ b/pcsync
@@ -1,6 +1,6 @@
 #!/bin/bash
 # ==================================================================
-# FILE     pcsync.sh
+# FILE     pcsync
 # MACHINE  all
 # INFO     syncs stuff from external HD to local HD and back, 
 #          using rsync
@@ -8,7 +8,7 @@
 #            formatting: cd /run/media/, login as root with su, 
 #            chown -R bruno:users bruno
 #
-# DATE     23.02.2014
+# DATE     24.02.2014
 # OWNER    Bischofberger
 # ==================================================================
 
@@ -59,8 +59,7 @@ if [[ $answer == up ]] ; then
 	if [[ $answer2 == y ]] ; then
 		if [[ $dry != "-n" ]] ; then  # handle dry-run option
 			echo "setting correct rights on $stick"
-			sudo chown -R $(hostname):users $stick \  # user handling for rsync --delete
-                || die "chown error"
+			sudo chown -R $(hostname):users $stick || die "chown error"  # user handling for rsync --delete
 		fi
 		rsync -avu "$dry" --delete --include-from="$includefile" $HOME/ $stick/ \
             || die "rsync error"
@@ -76,8 +75,7 @@ elif [[ $answer == down ]] ; then
 	if [[ $answer2 == y ]] ; then
 		if [[ $dry != "-n" ]] ; then
 			echo "setting correct rights on $stick"
-			sudo chown -R $(hostname):users $stick \
-                || die "chown error"
+			sudo chown -R $(hostname):users $stick || die "chown error"
 		fi
 		rsync -avu "$dry" --delete --include-from="$includefile" $stick/ $HOME/ \
             || die "rsync error"
