shellchecked

diff --git a/pdfpsize b/pdfpsize
--- a/pdfpsize
+++ b/pdfpsize
@@ -5,12 +5,11 @@
 # INFO     get size of pdf im mm
 #          depends on pdfinfo
 #
-# DATE     31.03.2016
+# DATE     26.09.2023
 # OWNER    Bischofberger
 # ==================================================================
 
 ONEPTS="0.3527778"
-LANDSCAPE=""
 
 die() {
 	echo -e "$0: Error: $1" >&2
@@ -22,14 +21,16 @@ swap() {
 }
 
 pts_to_mm() {
-  local unrounded=`echo | awk '{print '$ONEPTS' * '$1'}'`
+  local unrounded=""
+  unrounded=$(echo | awk '{print '$ONEPTS' * "$1"}')
   printf "%.1f" "$unrounded"
 }
 
 handleLandscape() {
-  local rot=`pdfinfo $1 | awk '/'Page\ rot:'/ {print $3}'` 
+  local rot=""
+  rot=$(pdfinfo "$1" | awk '/'Page\ rot:'/ {print $3}')
   if [[ "$rot" == "90" || "$rot" == "270" ]] ; then
-    swap $2 $3
+    swap "$2" "$3"
   fi
 }
 
@@ -40,14 +41,14 @@ if [[ "$#" != "1" ]] ; then
   die "give a pdf file as single argument"
 fi
 
-pdfinfo $1 || die "failed to extract pdf info"
+pdfinfo "$1" || die "failed to extract pdf info"
 
-SIZE_pts_X=`pdfinfo $1 | awk '/'Page\ size:'/ {print $3}'` 
-SIZE_pts_Y=`pdfinfo $1 | awk '/'Page\ size:'/ {print $5}'`
+SIZE_pts_X=$(pdfinfo "$1" | awk '/'Page\ size:'/ {print $3}') 
+SIZE_pts_Y=$(pdfinfo "$1" | awk '/'Page\ size:'/ {print $5}')
 
-SIZE_mm_X=`pts_to_mm $SIZE_pts_X`
-SIZE_mm_Y=`pts_to_mm $SIZE_pts_Y`
+SIZE_mm_X=$(pts_to_mm "$SIZE_pts_X")
+SIZE_mm_Y=$(pts_to_mm "$SIZE_pts_Y")
 
-handleLandscape $1 SIZE_mm_X SIZE_mm_Y
+handleLandscape "$1" SIZE_mm_X SIZE_mm_Y
 
 echo -e "\nPage size (mm): $SIZE_mm_X x $SIZE_mm_Y mm\n"
