inactive repos in seperate list

diff --git a/statemall b/statemall
--- a/statemall
+++ b/statemall
@@ -13,15 +13,23 @@
 #					 Cyan         0;36     Light Cyan    1;36
 #					 Light Gray   0;37     White         1;37
 #
-# DATE     01.05.2017
+# DATE     04.10.2018
 # OWNER    Bischofberger
 # ==================================================================
 
-GitHubReposFile="$HOME/Scripts/data/GitHubRepos.txt"
-LocalReposFile="$HOME/Scripts/data/LocalRepos.txt"
+GitPathLists="$HOME/Scripts/data/"
+GitOnGitHubFile="GitOnGitHub.txt"
+GitOnLocalFile="GitOnLocal.txt"
+GitInactiveFile="GitInactive.txt"
 COLOR1='\033[1;31m'
 COLOR2='\033[1;35m'
+COLOR3='\033[1;30m'
 NC='\033[0m'  # No Color
+
+die() {
+	echo -e "$0: Error: $1" >&2
+	exit 1
+}
 
 # arg1: ReposFile
 # arg2: Color
@@ -41,16 +49,38 @@ printRepos(){
 
 }
 
-echo -e "${COLOR1}=============${NC}"
-echo -e "${COLOR1}GitHub repos:${NC}"
-echo -e "${COLOR1}=============${NC}"
-printRepos $GitHubReposFile $COLOR1
 
-echo -e "\n"
+# ---- main routine ----
 
-echo -e "${COLOR2}============${NC}"
-echo -e "${COLOR2}Local repos:${NC}"
-echo -e "${COLOR2}============${NC}"
-printRepos $LocalReposFile $COLOR2
+# no argument given
+if [ -z "$1" ] ; then
+  echo -e "${COLOR1}=============${NC}"
+  echo -e "${COLOR1}GitHub repos:${NC}"
+  echo -e "${COLOR1}=============${NC}"
+  printRepos "$GitPathLists$GitOnGitHubFile" "$COLOR1"
+
+  echo -e "\n"
+
+  echo -e "${COLOR2}============${NC}"
+  echo -e "${COLOR2}Local repos:${NC}"
+  echo -e "${COLOR2}============${NC}"
+  printRepos "$GitPathLists$GitOnLocalFile" "$COLOR2"
+
+  exit 0
+fi
+
+# various options
+case "$1" in
+  "-i"|"--inactive")
+    echo -e "${COLOR3}===============${NC}"
+    echo -e "${COLOR3}Inactive repos:${NC}"
+    echo -e "${COLOR3}===============${NC}"
+    printRepos "$GitPathLists$GitInactiveFile" "$COLOR3"
+    exit 0
+    ;;
+  *)
+    die "invalid argument"
+    ;;
+esac
 
 exit 0
