improved volume handling (respect mute...)

diff --git a/vol b/vol
--- a/vol
+++ b/vol
@@ -3,46 +3,87 @@
 # FILE     vol
 # MACHINE  all
 # INFO     just some amixer wrapper
+#          volume is controled over an integer between 0 and 10
 #
-# DATE     14.05.2014
+# DATE     05.04.2016
 # OWNER    Bischofberger
 # ==================================================================
 
 die() {
-    echo -e "$0: Error: $1" >&2
-    exit 1
+  echo -e "$0: Error: $1" >&2
+  exit 1
 }
+
+# get volume and state [on|off]
+getMixerStatus() {
+  echo -e -n "current volume: "
+  amixer sget Master | awk '/Mono:/ {print $4 " " $6}'
+}
+
+# get volume as a (reusable number between 0 and 10)
+getVolume(){
+  local VOL=`amixer sget Master | awk '/Mono:/ {gsub(/[\[\]%]/,""); print $4}'`
+  let "VOL /= 10"
+  echo $VOL
+}
+
+# get state only [on|off]
+getStat() {
+  amixer sget Master | awk '/Mono:/ {gsub(/[\[\]]/,""); print $6}'
+}
+
+setMixer() {
+  amixer -q sset Master $1
+}
+
+# main -------------------------------------------------
 
 # no argument gives info
 if [ -z "$1" ] ; then
-    amixer sget Master
-    exit 0
+  getMixerStatus
+  exit 0
 fi
 
 # toggle mute, increase, decrease
 case "$1" in
-    "t")
-        amixer -q sset Master toggle
-        exit 0
-        ;;
-    "+")
-        amixer -q sset Master 5+
-        exit 0
-        ;;
-    "-")
-        amixer -q sset Master 5-
-        exit 0
-        ;;
-    *)
-        ;;
+  "t")
+    setMixer toggle
+    exit 0
+    ;;
+  "off")
+    setMixer off
+    exit 0
+    ;;
+  "on")
+    setMixer on
+    exit 0
+    ;;
+  "+")
+    setMixer 5+
+    exit 0
+    ;;
+  "-")
+    setMixer 5-
+    exit 0
+    ;;
+  "--getVol")
+    getVolume
+    exit 0
+    ;;
+  "--getStat")
+    getStat
+    exit 0
+    ;;
+  *)
+    ;;
 esac
 
 # check if argument is not a number between 0 and 10
 regex='^[0-9]$'
 if ! [[ $1 =~ $regex ]] && [[ $1 != 10 ]] ; then
-    die "not a (valid) number."
+  die "not a (valid) number."
 fi
 
 # set volume
 let "vol = 10 * $1"
-amixer -q sset Master $vol% unmute
+setMixer $vol% unmute
